### ISSUE TITLE
Downstream split tracking issue

### ISSUE THREAD

**Issue by zklaus** [conda-forge/udunits2-feedstock#52]
### Comment:

With #49 in, we now need to adapt the downstream feedstocks by removing `udunits2` from the run requirements.

Here is a list constructed from @xylar's search-fu in https://github.com/conda-forge/udunits2-feedstock/pull/48#issuecomment-1723252145.  When you pick up one from the list, please add your name and/or the PR after the feedstock. When it's successfully completed, tick the box :)

- [ ] ~~https://github.com/conda-forge/cdms2-feedstock~~ @xylar is not seeing `udunits2` here.
- [ ] https://github.com/conda-forge/cdo-feedstock
- [ ] https://github.com/conda-forge/cf_units-feedstock
- [ ] https://github.com/conda-forge/cfunits-feedstock
- [ ] ~~https://github.com/conda-forge/cmor-feedstock~~ CMOR wants to keep the dependency on `udunits2`, see https://github.com/conda-forge/cmor-feedstock/pull/67#issuecomment-1775937231
- [ ] https://github.com/conda-forge/enso_metrics-feedstock
- [ ] https://github.com/conda-forge/fimex-feedstock
- [x] https://github.com/conda-forge/genutil-feedstock - @xylar: https://github.com/conda-forge/genutil-feedstock/pull/26
- [ ] https://github.com/conda-forge/gimli.units-feedstock
- [ ] https://github.com/conda-forge/ncl-feedstock
- [x] https://github.com/conda-forge/nco-feedstock - @xylar: https://github.com/conda-forge/nco-feedstock/pull/184
- [x] https://github.com/conda-forge/ncview-feedstock
- [x] https://github.com/conda-forge/r-rnetcdf-feedstock
- [x] https://github.com/conda-forge/r-udunits2-feedstock
- [x] https://github.com/conda-forge/r-units-feedstock

**Comment by mfansler** [comment]
I'm happy to handle the `r-*` feedstocks.

**Comment by mfansler** [comment]
Downstream recipes for `r-rnetcdf`, `r-udunits2`, and `r-units` have been adjusted. ✅✅✅

**Comment by xylar** [comment]
Thanks @mfansler!
